### ISSUE TITLE
Crash when exporting to Excel in SpreadsheetLight document constructor

### ISSUE THREAD

**Issue by JoanCharmant** [Kinovea/Kinovea#165]
repro: File > Export spreadsheet > Microsoft Excel

The crash happens since System.Drawing.Common was updated, somewhere between may and july 2024.
The newer System.Drawing.Common is a dependency of OpenCVSharp4.Extensions.
The crash happens as soon as we call `new SpreadsheetLight.SLDocument()`
SpreadsheetLight doesn't have an update and apparently hasn't been updated since 3.5.0 in 2020. Forks exist but none of them are built for .NET Standard or .NET Framework.

Secondary issue, this low level exception is not caught by the try catch in SpreadsheetExporter.cs

```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=SpreadsheetLight
  StackTrace:
   at SpreadsheetLight.SLFont.SetFont(FontSchemeValues FontScheme, Double FontSize)
   at SpreadsheetLight.SLDocument.LoadStylesheet()
   at SpreadsheetLight.SLDocument..ctor()
   at Kinovea.ScreenManager.ExporterXLSX.Export(String path, MeasuredData md)
```

**Comment by JoanCharmant** [comment]
That sounds great, I'll check it out.

**Comment by JoanCharmant** [comment]
Fixed
